### ISSUE TITLE
デレステwikiの大幅編集について

### ISSUE THREAD

**Issue by menowgt** [noelex/Cindeck#1]
はじめまして。デレステwiki副管理人のMenowという者です。

この度、貴方の作成されたツールで参照されている「楽曲情報一覧」のページを
大幅に更新することが決定いたしました。
つきましては、ツールの動作確認等の相談をお願いしたくIssueよりご連絡いたしました。

他のメンバーと交えて相談を行いたい所存ですので、
ご都合の方がよろしければwiki編集メンバーへ登録をしていただき、
「編集者用掲示板」の方からコメントをいただければ幸いです。

お手数ですがご検討の程よろしくお願い致します。

**Comment by noelex** [comment]
ご連絡ありがとうございます。
wiki編集メンバーへ登録しましたので、この件についてはそちらで議論したいと思います。
こちらのissueは閉じさせていただきます。
